### ISSUE TITLE
web-ifc-three/picking-properties and web-ifc-viewer/picking won't work with multiple models

### ISSUE THREAD

**Issue by nelsonhp3** [IFCjs/hello-world#49]
When I add more than one model to the web-ifc-three/picking-properties example and when I try to select any element that doesn't belong to the first model it throws this error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at IfcAPI2.GetLine (bundle.js:75440:48)
    at WebIfcPropertyManager.getItemProperties (bundle.js:76763:27)
    at PropertyManager.getItemProperties (bundle.js:77775:30)
    at IFCManager.getItemProperties (bundle.js:79061:28)
    at pick (bundle.js:83427:33)
```
When doing the same with web-ifc-viewer/picking, it throws this error when the mouse is over any element:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'mesh')
    at ItemsMap.getGeometry (bundle.js:89496:49)
    at ItemsMap.generateGeometryIndexMap (bundle.js:89474:27)
    at SubsetCreator.createSubset (bundle.js:89606:18)
    at SubsetManager.createSubset (bundle.js:89751:31)
    at IFCManager.createSubset (bundle.js:92428:25)
    at IfcSelection.newSelection (bundle.js:92583:49)
    at IfcSelection.pick (bundle.js:92566:35)
    at async IfcSelector.prePickIfcItem (bundle.js:92667:9)
```
How should I fix these?

**Comment by agviegas** [comment]
Can you try loading the models using `await ifcLoader.loadAsync`? Probably the error happens because you are not awaiting the load of the first model before loading the second one.

**Comment by nelsonhp3** [comment]
Worked perfectly in web-ifc-viewer/picking, thanks!! But the same snippet of code doesn't work in web-ifc-three/picking-properties:

```javascript
const ifcModels = []
const ifcLoader = new IFCLoader()
ifcLoader.ifcManager.setWasmPath("../../../")

async function loadModel(url) {
    await ifcLoader.loadAsync(url, (ifcModel) => {
        ifcModels.push(ifcModel)
        scene.add(ifcModel) // Throws error
    })
}
/* error:
    THREE.Object3D.add: object not an instance of THREE.Object3D. 
    ProgressEvent {isTrusted: false, ...}
*/
```
I wonder why it doesn't work.

**Comment by agviegas** [comment]
This is how `loadAsync` should look like:

```js
const model = await ifcLoader.loadAsync(url);
ifcModels.push(ifcModel);
scene.add(ifcModel);
```
